spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/osiria

  jpa:
    hibernate:
      ddl-auto: update
    properties:
        show_sql: true
