spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret-key: ${SECRET_KEY}
  access-exp: ${ACCESS_EXP}
  refresh-exp: ${REFRESH_EXP}

holiday:
  api:
    url: ${HOLIDAY_URL}
    key: ${HOLIDAY_KEY}

cloud:
  aws:
    s3:
      bucket: ${BUCKET}
      access-key: ${IAM_ACCESS}
      secret-key: ${IAM_SECRET}
      region: ap-northeast-2

naver:
  access-key: ${NAVER_ACCESS_KEY}
  secret-key: ${NAVER_SECRET_KEY}
  service-id: ${NAVER_SERVICE_ID}
  sender: ${SENDER}

aes:
  secret:
    key: ${AES_SECRET_KEY}