spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:asdf}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/osiria?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:localhost}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret-key: jkfdlajdlsjfasjflsajffdjsafsjasfsfasfsfasfsf
  access-exp: 7200000
  refresh-exp: 604800000

holiday:
  api:
    url: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo
    key: XeH%2F%2BVCjgbP3vptu69aRe5qVXni4AjKklKptgFTbmD1wk9d084NTrJksblMg%2FgxzgrT6JlmA%2FAGXHmwM7thJYA%3D%3D

cloud:
  aws:
    s3:
      bucket: ${BUCKET:asdf}
      access-key: ${IAM_ACCESS:safs}
      secret-key: ${IAM_SECRET:ddd}
      region: ap-northeast-2