spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/osiria

  jpa:
    hibernate:
      ddl-auto: update
    properties:
        show_sql: true
  data:
    redis:
      port: 6379
      host: localhost
      database: 1

jwt:
  secret-key: ajsdkljfkja&(@)*()(DSFSSFD
  access-exp: 7200000
  refresh-exp: 604800000