spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret-key: ${JWT_SECRET}
  access-exp: 7200000
  refresh-exp: 604800000

holiday:
  api:
    url: ${HOLIDAY_URL}
    key: ${HOLIDAY_KEY}
