spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}

jwt:
  secret-key: jkfdlajdlsjfasjflsajffdjsafsjasfsfasfsfasfsf
  access-exp: 7200000
  refresh-exp: 604800000

holiday:
  api:
    url: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo
    key: XeH%2F%2BVCjgbP3vptu69aRe5qVXni4AjKklKptgFTbmD1wk9d084NTrJksblMg%2FgxzgrT6JlmA%2FAGXHmwM7thJYA%3D%3D\=