on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build
        env:
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: rlaaudwls1!
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/osiria?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
          REDIS_HOST: localhost
          BUCKET: osiria
          IAM_ACCESS: AKIA5GUZEBME73IZ32EJ
          IAM_SECRET: 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

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: 4mjeo
          password: dckr_pat_16sEnV04xo4g8JbzfjXuuRP5C7s

      - name: Build and Push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t 4mjeo/osiria .
          docker push 4mjeo/osiria

      - name: Connect EC2 & Deploy Docker Imgae
        uses: appleboy/ssh-action@master
        with:
          host: 43.203.50.105
          port: '22'
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd Osiria
            docker pull 4mjeo/osiria
            docker compose up -d